# Generated by Django 2.1.5 on 2019-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seller', '0002_auto_20190116_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=32)),
                ('salt', models.CharField(max_length=10)),
                ('activate_status', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='client_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('selected', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=True, to='Buyer.Client')),
            ],
        ),
        migrations.CreateModel(
            name='client_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=32, unique=True)),
                ('more_order_code', models.CharField(max_length=32)),
                ('total_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('disable', models.SmallIntegerField(default=0)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('pay_status', models.SmallIntegerField(default=0)),
                ('pay_time', models.DateTimeField(null=True)),
                ('pay_money', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('out_status', models.SmallIntegerField(default=0)),
                ('in_status', models.SmallIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=True, to='Buyer.Client')),
                ('seller', models.ForeignKey(on_delete=True, to='Seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='customer_order_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField()),
                ('disable', models.SmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('goods', models.ForeignKey(on_delete=True, to='Seller.Goods')),
                ('order', models.ForeignKey(on_delete=True, to='Buyer.client_order')),
            ],
        ),
        migrations.CreateModel(
            name='shop_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=True, to='Buyer.Client')),
                ('goods', models.ForeignKey(on_delete=True, to='Seller.Goods')),
            ],
        ),
    ]
